// tienda-Angular2/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpService } from '../services/http.service';
import { Response } from '@angular/http';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  emailValue = '';
  emailError = '';
  emailErrorMsg = 'Ingrese su correo.';
  passwordValue = '';
  passwordError = '';
  passwordErrorMsg = 'Ingrese la contraseña.';

  constructor(private httpService: HttpService, private router: Router) { }

  onChange(target) {
    this.validate(target.id, target.value);
  }

  loginKeyPress(e) {
    if (e.key == 'Enter') {
      if (e.target.id == 'password') {
        this.login();
      } else {
        document.getElementById('password').focus();
      }
    }
  }

  login() {
    if (this.emailValue != '' && this.passwordValue != '') {
      this.httpService.getUsers()
        .subscribe(
          (data: Response) => {
            let aux: any[] = [];
            let logged = false;
            for (let key in data) {
              if (data[key]['chrEmail'] == this.emailValue && data[key]['chrPassword'] == this.passwordValue) {
                logged = true;
                this.router.navigateByUrl('/dashboard');
              }
            }
            if (!logged) {
              this.passwordValue = '';
              this.passwordError = 'is-invalid';
              this.passwordErrorMsg = 'Contraseña incorrecta.';
            }
          }
        )
    } else {
      if (this.emailValue == '') {
        this.emailError = 'is-invalid';
        this.emailErrorMsg = 'Ingrese su correo.';
        if (this.passwordValue == '') {
          this.passwordError = 'is-invalid';
          this.passwordErrorMsg = 'Ingrese la contraseña.';
        }
      } else {
        this.validate('email', this.emailValue);
        if (this.validateEmail(this.emailValue)) {
          this.validate('password', this.passwordValue);
        }
      }
    }
  }

  private validate(input, value) {
    switch (input) {
      case 'email':
        value = value.trim();
        this.emailValue = value;
        if (value == '' || !this.validateEmail(value)) {
          this.emailError = 'is-invalid';
          this.emailErrorMsg = 'Ingrese un correo válido.';
        } else {
          this.emailError = '';
        }
        break;
      case 'password':
        this.passwordValue = value;
        if (value == '') {
          this.passwordError = 'is-invalid';
          this.passwordErrorMsg = 'Ingrese la contraseña.';
        } else {
          this.passwordError = '';
        }
        break;
      default:

    }
  }

  private validateEmail(email) {
    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(String(email).toLowerCase());
  }

  // addUser() {
  //   this.httpService.sendUser({ chrFullName: 'Brandon Shneider', chrEmail: 'brandon@mail.com', chrPassword: 'password' })
  //     .subscribe(
  //       (data: Response) => {
  //         console.log(data);
  //       }
  //     );
  // }
}

<div class="container-fluid login-container">
  <div class="row vertical-center">
    <div class="col-md-6 offset-md-3 col-lg-4 offset-lg-4">
      <h1>Inicia Sesión</h1>
      <form id="login-form">
        <div class="form-group">
          <label htmlFor="email">Correo electrónico</label>
          <input type="email" class="form-control {{emailError}}" value="{{emailValue}}" (input)="onChange($event.target)" (keypress)="loginKeyPress($event)" id="email" required #email/>
          <div class="invalid-feedback">{{emailErrorMsg}}</div>
        </div>
        <div class="form-group">
          <label htmlFor="password">Contraseña</label>
          <input type="password" class="form-control {{passwordError}}" value="{{passwordValue}}" (input)="onChange($event.target)" (keypress)="loginKeyPress($event)" id="password" required #password/>
          <div class="invalid-feedback">{{passwordErrorMsg}}</div>
        </div>
        <button type="button" class="btn btn-success" (click)="login(email.value, password.value)">Ingresar</button>
      </form>
    </div>
  </div>
</div>

// tienda-reactJS/client/login.jsx
import React from 'react';
import style from "./css/login.css";
import * as request from 'superagent';

class Login extends React.Component {

    constructor() {
        super()
    }
    componentWillMount(){

    }
    render() {
        return (
            <div className="row vertical-center">
                <div className="col-md-6 offset-md-3 col-lg-4 offset-lg-4 login-container">
                    <h1>Inicia Sesión</h1>
                    <form>
                        <div className="form-group">
                            <label htmlFor="email">Correo electrónico</label>
                            <input type="email" className="form-control" id="email" required/>
                            <div className="invalid-feedback">Ingrese correo.</div>
                        </div>
                        <div className="form-group">
                            <label htmlFor="password">Contraseña</label>
                            <input type="password" className="form-control" id="password" required/>
                            <div className="invalid-feedback">Ingrese contraseña.</div>
                        </div>
                        <button type="button" onClick={this.login} className="btn btn-success">Ingresar</button>
                    </form>
                </div>
            </div>
        )
    }
    componentDidMount() {

    }
    login() {
        // request.get('../backend/backend.php')
        //     .set({
        //         'API-Key': 'LndkOnelk2232nl23k',
        //         'Content-Type': 'application/json'
        //     })
        //     .end((err, res) => {
        //         console.log(res);
        //     });
    }
}

export default Login;
