// tienda-Angular2/src/app/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {

  filter = '';
  products = {
    aguacate: { name: "Aguacate", file: "aguacate.jpg", price: 1, quantity: 0, count: 1 },
    ajo: { name: "Ajo", file: "ajo.jpg", price: 2, quantity: 98, count: 1 },
    almendras: { name: "Almendras", file: "almendras.jpg", price: 3, quantity: 100, count: 1 },
    arandanos: { name: "Arándanos", file: "arandanos.jpg", price: 4, quantity: 100, count: 1 },
    brocoli: { name: "Brócoli", file: "brocoli.png", price: 5, quantity: 100, count: 1 },
    calabaza: { name: "Calabaza", file: "calabaza.jpg", price: 6, quantity: 100, count: 1 },
    canela: { name: "Canela", file: "canela.jpg", price: 7, quantity: 100, count: 1 },
    cebolla: { name: "Cebolla", file: "cebolla.jpg", price: 8, quantity: 100, count: 1 },
    fresa: { name: "Fresa", file: "fresa.jpg", price: 9, quantity: 100, count: 1 },
    kiwi: { name: "Kiwi", file: "kiwi.jpg", price: 10, quantity: 100, count: 1 },
    limon: { name: "Limón", file: "limon.jpg", price: 11, quantity: 100, count: 1 },
    lychee: { name: "Lychee", file: "lychee.jpg", price: 12, quantity: 100, count: 1 },
    maiz: { name: "Maíz", file: "maiz.jpg", price: 13, quantity: 100, count: 1 },
    manzana: { name: "Manzana", file: "manzana.jpg", price: 14, quantity: 100, count: 1 },
    naranja: { name: "Naranja", file: "naranja.jpg", price: 15, quantity: 100, count: 1 },
    papa: { name: "Papa", file: "papa.jpg", price: 16, quantity: 100, count: 1 },
    pasta: { name: "Pasta", file: "pasta.jpg", price: 17, quantity: 100, count: 1 },
    pimienta: { name: "Pimienta", file: "pimienta.jpg", price: 18, quantity: 100, count: 1 },
    repollo: { name: "Repollo", file: "repollo.jpg", price: 19, quantity: 100, count: 1 },
    tomate: { name: "Tomate", file: "tomate.jpg", price: 20, quantity: 100, count: 1 },
    zanahoria: { name: "Zanahoria", file: "zanahoria.jpg", price: 21, quantity: 100, count: 1 }
  };
  details = false;
  detailProduct = {};
  shoppingCart = {};

  constructor() {
    console.log(this.products)
  }

  ngOnInit() {
  }

  onFilter(value) {
      this.filter = value.trim();
  }

}

<div class="container-fluid fill-height dashboard-container">
  <div class="container no-padding-sides">
    <app-navbar [shoppingCart]="shoppingCart"></app-navbar>
    <div class="row no-margin-sides">
      <div class="col-12 top-content">
        <div class="row">
          <div class="col-md-9 title-container">
            <h1 *ngIf='!details'>Catálogo de productos</h1>
            <h1 *ngIf='details'>{{detailProduct.name}}</h1>
          </div>
          <div class="col-md-3 search-container" *ngIf='!details'>
            <p>¿Qué estás buscando?</p>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="search_addon"><img src="/img/ic_search.svg"/></span>
              </div>
              <input type="text" class="form-control" id="search" value="{{filter}}" (input)="onFilter($event.target.value)" />
            </div>
          </div>
        </div>
        <hr/>
      </div>
    </div>
    <div class="row no-margin-sides">
      <div class="col-12 catalog-content">
        <div class="row no-margin-sides" *ngFor="let row of products | filterProduct: filter">
          <div class="card col-md-3" *ngFor="let product of row | keyvalue">
            <img class="card-img-top" src="img/{{row[product].file}}" alt="Card image cap" />
            <div class="card-body no-padding-sides">
              <h5 class="card-title">{{row[product].name}}</h5>
              <p class="card-text"><strong>Precio: </strong>${{row[product].price}}</p>
              <p class="card-text"><strong>Unidades disponibles: </strong>{{row[product].quantity}}</p>
              <div class="row no-margin-sides card-bottom">
                <div class="col-5 col-md-12 col-lg-5 no-padding-sides">
                  <button class="btn btn-primary" id="details_{{row[product].name | lowercase | noSpecialChr}}">Ver más</button>
                </div>
                <div class="col-7 col-md-12 col-lg-7 no-padding-sides">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <button class="btn btn-secondary" type="button" id="count_{{row[product].name | lowercase | noSpecialChr}}">Añadir</button>
                    </div>
                    <input type="number" class="form-control" id="input_{{row[product].name | lowercase | noSpecialChr}}" value="{{row[product].count}}" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// tienda-reactJS/client/app/components/Dashboard.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import * as request from 'superagent';

import style from '../assets/css/dashboard.css';

import Navbar from './Navbar.jsx';

class Dashboard extends React.Component {

    constructor() {
        super()
        this.createCatalog = this.createCatalog.bind(this);
        this.state = {
            filter: '',
            products: {
                'aguacate': {
                    'name': 'Aguacate',
                    'file': 'aguacate.jpg',
                    'price': 5,
                    'quantity': 46,
                    'count' : 1
                },
                'ajo': {
                    'name': 'Ajo',
                    'file': 'ajo.jpg',
                    'price': 2,
                    'quantity': 78,
                    'count' : 1
                },
                'almendras': {
                    'name': 'Almendras',
                    'file': 'almendras.jpg',
                    'price': 8,
                    'quantity': 29,
                    'count' : 1
                },
                'arándanos': {
                    'name': 'Arándanos',
                    'file': 'arandanos.jpg',
                    'price': 6,
                    'quantity': 39,
                    'count' : 1
                },
                'brócoli': {
                    'name': 'Brócoli',
                    'file': 'brocoli.png',
                    'price': 10,
                    'quantity': 87,
                    'count' : 1
                }
            }
        }
    }

    onAddChange(e) {
        let value = e.target.value;
        if (value > 0) {
            let product = e.target.id.substr(6);
            let products = Object.assign({}, this.state.products);    //creating copy of object
            products[product].count = value;                        //updating value
            this.setState({products});
        }
    }

    render() {
        return (
            <div className="container-fluid fill-height dashboard-container">
                <div className="container">
                    <Navbar />
                    <div className="row no-margin-sides product-container">
                        <div className="col-12 top-content">
                            <div className="row">
                                <div className="col-md-9 title-container">
                                    <h1>Catálogo de productos</h1>
                                </div>
                                <div className="col-md-3 search-container">
                                    <p>¿Qué estás buscando?</p>
                                    <div className="input-group">
                                        <div className="input-group-prepend">
                                            <span className="input-group-text" id="search_addon"><img src="/assets/img/ic_search.svg"/></span>
                                        </div>
                                        <input type="text" className="form-control" id="search"/>
                                    </div>
                                </div>
                            </div>
                            <hr />
                        </div>
                        <div className="col-12 catalog-content">
                            {this.createCatalog()}
                        </div>
                    </div>
                </div>
            </div>
        )
    }

    createCatalog() {
        let catalog = [];
        let row = [];

        for(var product in this.state.products){
            if (this.state.filter != '' && product.indexOf(this.state.filter) == -1) {
                continue;
            }
            row.push(
                <div className="card col-md-3" key={'card-' + product}>
                    <img className="card-img-top" src={'/assets/img/' + this.state.products[product].file} alt="Card image cap" />
                    <div className="card-body no-padding-sides">
                        <h5 className="card-title">{this.state.products[product].name}</h5>
                        <p className="card-text"><strong>Precio: </strong>${this.state.products[product].price}</p>
                        <p className="card-text"><strong>Unidades disponibles: </strong>{this.state.products[product].quantity}</p>
                        <div className="row no-margin-sides card-bottom">
                            <div className="col-sm-5 col-md-12 col-lg-5 no-padding-sides">
                                <button className="btn btn-primary">Ver más</button>
                            </div>
                            <div className="col-sm-7 col-md-12 col-lg-7 no-padding-sides">
                                <div className="input-group">
                                    <div className="input-group-prepend">
                                        <button className="btn btn-outline-secondary" type="button" id={"count_" + this.state.products[product].name.toLowerCase()}>Añadir</button>
                                    </div>
                                    <input type="number" className="form-control" id={"input_" + this.state.products[product].name.toLowerCase()} value={this.state.products[product].count} onChange={e => this.onAddChange(e)}/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            );
            if (row.length % 4 == 0) {
                catalog.push(
                    <div className="row no-margin-sides" key={row.length}>{row}</div>
                );
            }
        }
        if (catalog == '') {
            catalog.push(
                <div className="row no-margin-sides" key={row.length}>{row}</div>
            );
        }
        return catalog;
    }
}

export default Dashboard;
