// tienda-Angular2/src/app/navbar/navbar.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { HelperService } from '../services/helpers.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  @Input() shoppingCart: Object;

  constructor(private helper: HelperService) { }

  ngOnInit() { }
  isCartEmpty(){
      return this.helper.isObjectEmpty(this.shoppingCart);
  }
  cartLength(){
      return this.helper.objectLength(this.shoppingCart);
  }

}

<div class="navbar sticky-top navbar-light bg-light navbar-expand">
  <a routerLink="/dashboard">La Bodega</a>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a routerLink="/dashboard"><img src="/img/ic_dashboard.svg"/></a>
    </li>
    <li class="nav-item">
      <a routerLink="/cart"><img src="/img/ic_shopping.svg"/><span *ngIf="!isCartEmpty()" class="badge badge-pill badge-danger">{{cartLength()}}</span></a>
    </li>
    <li class="nav-item">
      <a routerLink="/dashboard"><img src="/img/ic_inbox.svg"/></a>
    </li>
    <li class="nav-item">
      <a routerLink="/login"><img src="/img/ic_logout.svg"/></a>
    </li>
  </ul>
</div>

// tienda-reactJS/client/app/components/Navbar.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import * as request from 'superagent';

import style from '../assets/css/navbar.css';

import { isObjectEmpty, objectLength } from './helpers/helpers.jsx'

class Navbar extends React.Component {

    constructor(props) {
        super(props)
        this.state = {

        }
    }

    render() {
        let badge = [];
        if (objectLength(this.props.shoppingCart) > 0) {
            badge.push(
                <span className="badge badge-pill badge-danger" key="kart_badge">{objectLength(this.props.shoppingCart)}</span>
            );
        }
        return (
            <div className="navbar sticky-top navbar-light bg-light navbar-expand">
                <Link to="/dashboard">La Bodega</Link>
                <ul className="navbar-nav ml-auto">
                    <li className="nav-item">
                        <Link to="/dashboard"><img src="/assets/img/ic_dashboard.svg"/></Link>
                    </li>
                    <li className="nav-item">
                        <Link to="/cart"><img src="/assets/img/ic_shopping.svg"/>{badge}</Link>

                    </li>
                    <li className="nav-item">
                        <Link to="/dashboard"><img src="/assets/img/ic_inbox.svg"/></Link>
                    </li>
                    <li className="nav-item">
                        <Link to="/"><img src="/assets/img/ic_logout.svg"/></Link>
                    </li>
                </ul>
            </div>
        )
    }
}

export default Navbar;
